### ISSUE TITLE
根本用不了啊

### ISSUE THREAD

**Issue by zcfire2017** [kiryu1223/ExpressionTree#1]
按照文档写了，完全没用啊，启动就报错

**Comment by zcfire2017** [comment]
![image](https://github.com/user-attachments/assets/e0ec33c2-e479-4bff-9237-43e00d4bc097)

**Comment by kiryu1223** [comment]
不可以是**方法引用**，必须是**纯Lambda表达式**

**Comment by kiryu1223** [comment]
忘记给方法引用加错误提示了，下版本加上

**Comment by zcfire2017** [comment]
![image](https://github.com/user-attachments/assets/4c6d6bf5-ec62-41b3-8f6b-b838a65458d8)
还是不对啊，你提供一个可以运行的代码呢？

**Comment by kiryu1223** [comment]
> ![image](https://private-user-images.githubusercontent.com/34852479/375195610-4c6d6bf5-ec62-41b3-8f6b-b838a65458d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg1Mjg4MzksIm5iZiI6MTcyODUyODUzOSwicGF0aCI6Ii8zNDg1MjQ3OS8zNzUxOTU2MTAtNGM2ZDZiZjUtZWM2Mi00MWIzLThmNmItYjgzOGE2NTQ1OGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDEwVDAyNDg1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMzdkYTgzZjg3MzY3YTUxYTE3YzFmMGRjZmIwNjBmZWIwM2EyMTg3YzFkNjhkZWFiYjUyOWEyMTE0YmQzNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iBuih4tHC-DBC0TRVnO_a2Ep9sgJvJmMxmdGSaNTxFU) 还是不对啊，你提供一个可以运行的代码呢？

暂时不可以这样写，你必须把lambda直接写到参数里，不能用对象的方式去传递

**Comment by kiryu1223** [comment]
test(s -> {int a = 1;})

**Comment by zcfire2017** [comment]
![image](https://github.com/user-attachments/assets/80a66f47-2a57-46ff-99f3-5dd7d38a2c6e)

一样的，没用，会不会是因为我是jdk17的原因

**Comment by kiryu1223** [comment]
编译通过了吗
